// Code generated by counterfeiter. DO NOT EDIT.
package applychangesfakes

import (
	"sync"
)

type FakeReportPrinter struct {
	PrintReportStub        func(string)
	printReportMutex       sync.RWMutex
	printReportArgsForCall []struct {
		arg1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeReportPrinter) PrintReport(arg1 string) {
	fake.printReportMutex.Lock()
	fake.printReportArgsForCall = append(fake.printReportArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("PrintReport", []interface{}{arg1})
	fake.printReportMutex.Unlock()
	if fake.PrintReportStub != nil {
		fake.PrintReportStub(arg1)
	}
}

func (fake *FakeReportPrinter) PrintReportCallCount() int {
	fake.printReportMutex.RLock()
	defer fake.printReportMutex.RUnlock()
	return len(fake.printReportArgsForCall)
}

func (fake *FakeReportPrinter) PrintReportArgsForCall(i int) string {
	fake.printReportMutex.RLock()
	defer fake.printReportMutex.RUnlock()
	return fake.printReportArgsForCall[i].arg1
}

func (fake *FakeReportPrinter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.printReportMutex.RLock()
	defer fake.printReportMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeReportPrinter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
