package cmd

import (
	"fmt"
	"os"

	"github.com/pivotal-cloudops/omen/internal/tile"
	"github.com/spf13/cobra"
)

var stagedTilesCmd = &cobra.Command{
	Use:   "staged-tiles",
	Short: "produce last staged changes for all tiles",
	Run: func(cmd *cobra.Command, args []string) {
		if output_dir == "" {
			fmt.Println("an output path is required, please set with the output-dir flag")
			os.Exit(1)
		}

		client := getOpsmanClient()
		tileLoader := tile.NewTilesLoader(client)

		tiles, err := tileLoader.LoadStaged(true)
		if err != nil {
			printReport("", err)
		}

		err = tiles.Write(output_dir)
		if err != nil {
			printReport("", err)
		}

		fmt.Println("tiles written to", output_dir)
	},
}

var output_dir string

func init() {
	stagedTilesCmd.Flags().StringVarP(&output_dir, "output-dir", "o", "", "required - sets where to put the files generated by this command")
}
