package cmd

import (
	"fmt"
	"os"

	"github.com/pivotal-cloudops/omen/internal/tile"
	"github.com/spf13/cobra"
)

var stagedTilesCmd = &cobra.Command{
	Use:   "staged-tiles",
	Short: "produce last staged changes for all tiles",
	Run: func(cmd *cobra.Command, args []string) {
		if outputDir == "" {
			fmt.Println("an output path is required, please set with the output-dir flag")
			os.Exit(1)
		}

		client := setupOpsmanClient()
		tileLoader := tile.NewTilesLoader(client)

		tiles, err := tileLoader.LoadStaged(true)
		if err != nil {
			rp.Fail(err)
		}

		err = tiles.Write(outputDir)
		if err != nil {
			rp.Fail(err)
		}

		rp.PrintReport(fmt.Sprintf("tiles written to %s\n", outputDir))
	},
}

var outputDir string

func init() {
	stagedTilesCmd.Flags().StringVarP(&outputDir, "output-dir", "o", "", "required - sets where to put the files generated by this command")
}
